Force data source files to be considered UTF-8
Fixes the error

    RuntimeError: Could not read content/libraries.md because the file is not valid US-ASCII.